### ISSUE TITLE
CORINNA ISN'T OPTIMIZED

### ISSUE THREAD

**Issue by hellas-scholar** [Ovid/Corinna#1]
Currently, there is an issue with Perl's language capabilities. There are multiple languages to choose from, and Corinna is rendered incapable of delivering optimized performance and run quality due to information overload in the software. 

The program needs a way to choose between paths at any given fork.

**Comment by Ovid** [comment]
I am unsure what you're saying. Corinna's not "optimized" because we're trying to make it right and _then_ make it fast. However, the `Object::Pad` test bed has already shown great performance, often outperforming raw Perl OO in terms of both speed and memory consumption. And that's _before_ optimization.

> The program needs a way to choose between paths at any given fork.

I have no idea what that means.

If you can give concrete examples, preferably with code, that would be great. Otherwise, I'll be closing this ticket.

**Comment by Ovid** [comment]
Closing. No response from original reporter.
